//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaCompeticao.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Artist_has_Competition
    {
        public int Artist_idArtist { get; set; }
        public int Battle_idBattle { get; set; }
        public int idArtist_has_Competition { get; set; }
    
        public virtual Artist Artist { get; set; }
        public virtual Battle Battle { get; set; }
    }
}
