//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaCompeticao.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Instrument
    {
        public int idInstrument { get; set; }
        public string InstrumentType { get; set; }
        public int Music_idMusic { get; set; }
        public int Member_idMember { get; set; }
    
        public virtual Member Member { get; set; }
        public virtual Music Music { get; set; }
    }
}
